dwindle {
  # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
  pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
  preserve_split = yes # mantém a direção do split ao redimensionar
  force_split = 2 # novas janelas sempre abrem à direita/abaixo, criando o efeito espiral
}

master {
  # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
  mfact = 0.5
}

gestures {
  # See https://wiki.hyprland.org/Configuring/Variables/ for more
  # workspace_swipe = off
}
